import java.util.Scanner;

public class UserInterface {

    Scanner console = new Scanner(System.in);
    consoleColors cc = new consoleColors();
    InputCheck ic = new InputCheck();

    public UserInterface(){

        String userInput = "";                          //Uncertain if input should be of String type

        while(!userInput.equals("/quit")) {

            System.out.println("Welcome to the Database program");
            cc.printTxtBlue("1. Select data\n")
                    .printTxtYellow("2. Update data\n")
                    .printTxtRed("3. Delete data\n")
                    .printTxtPurple("4. Insert data\n")
                    .print(false);

            System.out.print("Please choose: ");
            userInput = console.next();
            cc.clearTxtBuffer();

                switch (userInput.charAt(0)) {
                    case '1':
                        cc.printTxtBlue("\n\n" + ic.selectLogic2().toString()).print(true);
                        break;
                    case '2':
                        update();
                        break;
                    case '3':
                        delete();
                        break;
                    case '4':
                        insert();
                        //db.insertProduct(productName, productLocation, productPrice);
                        break;
                }
            System.out.println();
            cc.clearTxtBuffer();
            }
    }

    private void update(){

    }

    private void delete(){

    }

    private void insert(){
        cc.printTxtPurple("Product Name: ").print(false);
        String nameInput = console.next();
        cc.clearTxtBuffer();

        cc.printTxtPurple("Product Price: ").print(false);
        int priceInput = console.nextInt();
        cc.clearTxtBuffer();

        console.nextLine();                     //For the empty \n token generated by nextInt

        cc.printTxtPurple("Product Location: ").print(false);
        String locationInput = console.nextLine();
        cc.clearTxtBuffer();

        if(ic.insertIntoDB(nameInput, priceInput, locationInput)) {
            cc.printTxtPurple("Item successfully added to Database").print(true);
        } else {
            cc.printTxtPurple("Item not added, illegal characters included").print(true);
        }
        cc.clearTxtBuffer();
    }
}